# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-xzt4pJMK-wHEdapoFFONtsQM1m9PLAU
"""

import pandas as pd

# Load data
df = pd.read_csv("/content/drive/MyDrive/AI-ML + Python /DEATH DATA.csv")

# Remove spaces from column names
df.columns = df.columns.str.strip()

# Remove duplicates
df.drop_duplicates(inplace=True)

# Convert data types
df['Year'] = df['Year'].astype(int)
df['Month'] = df['Month'].astype(int)

# Ensure numeric columns are correct
cols = ['DeathRegMale','DeathRegFemale','DeathRegCount',
        'CertiIssueCountMale','CertiIssueCountFeMale','CertiIssueCount']

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Fill any accidental NaN after conversion
df.fillna(0, inplace=True)

# Gender ratio
df['Gender_Ratio'] = df['DeathRegMale'] / (df['DeathRegFemale'] + 1)

# Efficiency (certificate issued vs deaths)
df['Efficiency'] = df['CertiIssueCount'] / (df['DeathRegCount'] + 1)

# Gap analysis
df['Gap'] = df['DeathRegCount'] - df['CertiIssueCount']

# Create date column (useful later)
df['Date'] = pd.to_datetime(df[['Year','Month']].assign(DAY=1))

# Sort properly
df = df.sort_values(by=['Year','Month'])

df.to_csv("clean_death_data.csv", index=False)

import os
print(os.getcwd())

import os
print(os.listdir('/content'))
